version: '3'

services:
  javbus:
    build: .
    container_name: javbus-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./buspic:/app/buspic
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 